// <auto-generated />
using Db.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Db.Migrations
{
    [DbContext(typeof(GameDb))]
    partial class GameDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Db.Models.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weapon")
                        .HasColumnType("integer");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            ArmorClass = 10,
                            AttackModifier = 10,
                            AttackPerRound = 3,
                            Damage = 5,
                            DamageModifier = 4,
                            HitPoints = 79,
                            Name = "Лось",
                            Weapon = 10
                        },
                        new
                        {
                            MonsterId = 2,
                            ArmorClass = 4,
                            AttackModifier = 4,
                            AttackPerRound = 2,
                            Damage = 4,
                            DamageModifier = 1,
                            HitPoints = 20,
                            Name = "Кошка",
                            Weapon = 3
                        },
                        new
                        {
                            MonsterId = 3,
                            ArmorClass = 10,
                            AttackModifier = 1,
                            AttackPerRound = 2,
                            Damage = 2,
                            DamageModifier = 3,
                            HitPoints = 50,
                            Name = "Амерго",
                            Weapon = 3
                        },
                        new
                        {
                            MonsterId = 4,
                            ArmorClass = 2,
                            AttackModifier = 4,
                            AttackPerRound = 2,
                            Damage = 1,
                            DamageModifier = 3,
                            HitPoints = 69,
                            Name = "Дерро",
                            Weapon = 1
                        },
                        new
                        {
                            MonsterId = 5,
                            ArmorClass = 11,
                            AttackModifier = 2,
                            AttackPerRound = 4,
                            Damage = 6,
                            DamageModifier = 4,
                            HitPoints = 80,
                            Name = "Савид",
                            Weapon = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
